Add support for Solaris 10 with opencsw python package

diff --git a/dfpython/python27 b/dfpython/python27
--- a/dfpython/python27
+++ b/dfpython/python27
@@ -1,3 +1,10 @@
 #!/bin/sh
-source /opt/rh/python27/enable
-exec python "$@"
+if [ -f /etc/redhat-release ]; then
+	source /opt/rh/python27/enable
+	exec python "$@"
+elif [ `uname -s` = "SunOS" ]; then
+	exec /opt/csw/bin/python "$@"
+else
+	echo "Unable to determine which python to use"
+	exit 2
+fi
